# Generated by Django 6.0 on 2025-12-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_unique_event_date'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_per_user_event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('email', 'event'), name='unique_ticket_per_email_event'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
